#pragma once

#undef  MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL       20
#undef  MOUSEKEY_DELAY
#define MOUSEKEY_DELAY          0
#undef  MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX    60
#undef  MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED      7
#undef  MOUSEKEY_WHEEL_DELAY
#define MOUSEKEY_WHEEL_DELAY    0

#define FORCE_NKRO

#undef USB_POLLING_INTERVAL_MS
#define USB_POLLING_INTERVAL_MS 1

/* Set 0 if debouncing isn't needed */
#undef DEBOUNCE
#define DEBOUNCE  1

#define NUM_LAYERS 5
#define LAYER_STATE_8BIT

#define DEBUG_MATRIX_SCAN_RATE

#define MASTER_LEFT

#define SPLIT_USB_DETECT
#define SPLIT_WATCHDOG_ENABLE
#define SPLIT_WATCHDOG_TIMEOUT 8000
#define SPLIT_USB_TIMEOUT 5000
#define FORCED_SYNC_THROTTLE_MS 5000
#define SELECT_SOFT_SERIAL_SPEED 2
//#define SERIAL_USART_SPEED 115200
#define SPLIT_MAX_CONNECTION_ERRORS 20


#undef ST7565_ENABLE
#ifdef ST7565_ENABLE
#define SPLIT_LAYER_STATE_ENABLE
#define ST7565_TIMEOUT 0
//#define usb_lld_disconnect_bus(usbp) do {} while(0)
#endif
